cleanup, fix kpi data
luabase/definite-chartlib pull request #82
Opened 2024-02-07 23:21 UTC by kreppi92

2024-02-07 23:25 UTC, kreppi92 commented
@mharrisb1 can we confirm this is the expected behaviour and that the chartsettings shouldnt be displaying "dimensions"

2024-02-07 23:26 UTC, kreppi92 commented on dist/index.js
> +      ]
@mharrisb1 i added this, because when i set datasetIndex to '1' it was not displaying. I would assume that it would select the second index of the value in the array for source. However source is an array of arrays. is this expected?

2024-02-08 01:38 UTC, mharrisb1 commented
> can we confirm this is the expected behaviour and that the chartsettings shouldnt be displaying "dimensions"

Yes that's expected. KPI/BigNum charts currently do not make use of dimensions, just a single metric.

2024-02-08 01:42 UTC, mharrisb1 commented on dist/index.js
> +      ]
> datasetIndex to '1' 

This is only used when transformations are done to the source data but for KPI charts the raw source data is used. 

I don't think any of this should have needed to be changed. Should just be a frontend change in the UI to select the select column at index `i`. If you're passing the column index to the config in the FE then everything should work.

2024-02-08 01:44 UTC, mharrisb1 commented
Please don't merge this. The cleanup of the mock data is fine but the change to determine series for KPI chart is not

2024-02-08 14:51 UTC, kreppi92 commented
> Please don't merge this. The cleanup of the mock data is fine but the change to determine series for KPI chart is not

the bug i am trying to fix here is that when the user selects a different metric in the chart settings, the metric does not update

2024-02-08 16:23 UTC, mharrisb1 commented
So you would end up with an ECOption object that looks like this:

```js
option = {
      ...,
      dataset: [
        {
          dimensions: ["mrrA", "mrrB"],
          source: [
            [50000, 60000],
          ]
        },
        {
          dimensions: ["mrrB"],
          source: [
            [60000],
          ]
        }
      ],
      ...,
      series: [{
        type: "gauge",
        datasetIndex: 1,
        radius: "0%",
        splitLine: {
          show: false
        },
        axisTick: {
          show: false,
        },
        axisLabel: {
          show: false
        },
        pointer: {
          show: false
        },
        title: {
          show: false
        },
        detail: {
          show: true,
          fontSize: 42,
        },
      }],
      ...,
};
```

2024-02-08 19:27 UTC, kreppi92 commented
> So you would end up with an ECOption object that looks like this:
> 
> ```js
> option = {
>       ...,
>       dataset: [
>         {
>           dimensions: ["mrrA", "mrrB"],
>           source: [
>             [50000, 60000],
>           ]
>         },
>         {
>           dimensions: ["mrrB"],
>           source: [
>             [60000],
>           ]
>         }
>       ],
>       ...,
>       series: [{
>         type: "gauge",
>         datasetIndex: 1,
>         radius: "0%",
>         splitLine: {
>           show: false
>         },
>         axisTick: {
>           show: false,
>         },
>         axisLabel: {
>           show: false
>         },
>         pointer: {
>           show: false
>         },
>         title: {
>           show: false
>         },
>         detail: {
>           show: true,
>           fontSize: 42,
>         },
>       }],
>       ...,
> };
> ```

ok I went with creating a new dataset so that the logic in the FE does not need to be recreated for slack, etc..

2024-02-08 20:44 UTC, kreppi92 commented on src/determine/datasets.ts
> +
@mharrisb1

2024-02-08 20:46 UTC, mharrisb1 requested changes

2024-02-08 20:54 UTC, kreppi92 commented on src/determine/datasets.ts
> +
```
    const name = df.columns.get(metric.index);
    const type = chart.getChartType();
    dataset.id = `${metric.index}::${type}::${datasets.length}::${name}::${metric.id}`;
    datasets.push(selectedMetricDataset);
```

2024-02-08 21:00 UTC, mharrisb1 requested changes

2024-02-08 21:00 UTC, mharrisb1 commented on src/determine/datasets.ts
> +    dataset.id = `${metric.index}::${type}::${datasets.length}::${name}::${metric.id}`;
make this `selectedMetricDataset.id = ...` and you should be good to go.

The test output should have an ID on the second dataset

2024-02-08 21:03 UTC, kreppi92 commented on src/determine/datasets.ts
> +    dataset.id = `${metric.index}::${type}::${datasets.length}::${name}::${metric.id}`;
whoops good catch

2024-02-08 21:35 UTC, kreppi92 reviewed
ok

2024-02-08 21:47 UTC, merged